DO $$ DECLARE
  r RECORD;
BEGIN
  FOR r IN (SELECT tablename FROM pg_tables WHERE schemaname = 'public') LOOP
    EXECUTE 'TRUNCATE TABLE ' || quote_ident(r.tablename) || ' CASCADE;';
  END LOOP;
END $$;

ALTER SEQUENCE "Animal_id_seq" RESTART WITH 1;
ALTER SEQUENCE "Appointment_id_seq" RESTART WITH 1;
ALTER SEQUENCE "Pet_id_seq" RESTART WITH 1;
ALTER SEQUENCE "Review_id_seq" RESTART WITH 1;
ALTER SEQUENCE "User_id_seq" RESTART WITH 1;
ALTER SEQUENCE "Vet_id_seq" RESTART WITH 1;

ALTER TABLE "Animal" DISABLE TRIGGER ALL;
ALTER TABLE "Appointment" DISABLE TRIGGER ALL;
ALTER TABLE "Pet" DISABLE TRIGGER ALL;
ALTER TABLE "Review" DISABLE TRIGGER ALL;
ALTER TABLE "User" DISABLE TRIGGER ALL;
ALTER TABLE "Vet" DISABLE TRIGGER ALL;
